# 异常处理

## 1. 总体说明

UnifiedSimpleMappingExceptionResolver继承SimpleMappingExceptionResolver，覆写doResolveException与logException方法，让它能够同时处理正常请求的异常与ajax请求的异常。这样就要求DAO, Service, Controller三层的异常经过异常转译（异常提示信息设置为对业务处理更友好的提示），统一抛出，让UnifiedSimpleMappingExceptionResolver处理。

```java
throw new RuntimeException("对业务处理更友好的提示信息", ex);
```

**待讨论：**我觉得自定义异常类没有必要了。因为它们除了类名，其他的结构都一样，只要`异常提示信息`设置好就行。

## 2. 正常请求的异常处理

正常请求异常返回页面配置（spring-mvc.xml）:

```xml
<!-- 异常解析器：包括Ajax异常 -->
<bean id="exceptionResolver" class="com.ailk.srd.framework.core.exception.UnifiedSimpleMappingExceptionResolver">
	<property name="warnLogCategory" value="DEBUG" />
	<property name="defaultErrorView">
		<value>/error/error</value>
	</property>
	<property name="exceptionMappings">
		<props>
			<prop key="org.springframework.web.multipart.MaxUploadSizeExceededException">/error/error</prop>
			<prop key="com.ailk.srd.framework.core.exception.BusinessException">/error/error</prop>
			<prop key="java.lang.Exception">/error/error</prop>
			<prop key="java.lang.Throwable">/error/error</prop>
			<prop key="java.lang.RuntimeException">/error/error</prop>
			<prop key="java.sql.SQLException">/error/error</prop>
		</props>
	</property>
</bean>
```

**待讨论：**正常情况下（非ajax），日志拦截器如何获取处理结果？直接在controller里面OperateLogHolder.getOperateLog().setXXX()？？

## 3. Ajax请求的异常处理

UnifiedSimpleMappingExceptionResolver类里处理ajax异常的代码：

```java
try {  
    PrintWriter writer = response.getWriter();
    System.out.println("进行Ajax异常处理！！");
    // 转成json写回到请求的地方
    writer.write(JsonConvertHelper.nonEmptyMapper().toJson(AjaxUtils.exception(ex.getMessage())));  
    writer.flush();
} catch (IOException e) {  
    e.printStackTrace();  
}
```
创建一个AjaxUtils.exception(ex.getMessage())，转成json写回到请求的地方。

定义一个Ajax请求返回结果对象AjaxResult，所有的ajax请求返回统一采用AjaxResult，其结构如下：

```java
// 结果状态
private int tag;
// 结果提示信息
private String message;
// 你的业务数据
private Object data;

```

通过静态方法创建返回该对象：

```java
// 状态标识
private final static int FAILED = 0; // 失败
private final static int SUCCESS = 1; // 成功
private final static int EXCEPTION = 2; // 异常
// 创建返回实例
AjaxUtils.success(); // 成功
AjaxUtils.failed(); // 失败
AjaxUtils.exception(); // 异常

@RequestMapping(value="/ajaxGet", method=RequestMethod.GET, produces=MediaType.APPLICATION_JSON_VALUE)
public @ResponseBody AjaxResult ajax(@RequestParam("name") String name, 
                                     @RequestParam("time") String time) throws Exception {
	AjaxResult result = null;
    try {
        // 业务数据
        String[] args = new String[]{name, time};
        result = AjaxUtils.success("办理成功！", args);
        //new ServiceException().service();
    } catch (Exception e) {
        throw new AjaxException("Ajax异常异常异常！！！", e);
    } 
    return result;
}

```

jsp页面上判断：

```javascript
$.ajax({
	type: 'GET',
    url: "<c:url value='/ajaxGet' />",
    contentType: 'application/json',
    data: {name: "John", time: "2pm"},
    dataType: 'json',
    success: function(result) {
		// 返回结果{"tag":1,"message":"办理成功！","data":["John","2pm"]}
    	if(result.tag === 1) {
    		// do success thing
    	} else if(result.tag === 2) {
    		// oops cause exception
    	} else {
    		// failed?
    	}
		// 返回状态写一个公共方法处理？？？
    	// 获取业务数据：result.data
    },
    error : function(jqXHR, textStatus, errorThrown) {
        alert(errorThrown);
    },
    complete : function(jqXHR, textStatus) {
        //alert(textStatus);
    }
});

```